### PR TITLE
Re enable pacemaker force import

### PR DESCRIPTION
**Pull request by tanabarr**
counterpart patch for https://github.com/intel-hpdd/intel-manager-for-lustre/pull/317

reverts the commits necessary to re-enable the use of force import when  pacemaker issues import

### CODE REVIEW

**Comment by jgrund** [comment]
> Does import -f get blocked by MMP or does it override MMP?

blocked.

```
 zpool import zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk1 -f
cannot import 'zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk1': pool is imported on host 'lotus-34vm5' (hostid=5a0ecc82).
Export the pool on the other system, then run 'zpool import'.
```

**Comment by brianjmurrell** [comment]
> blocked.

And so if you kill _lotus-34vm5_ the `zpool import zfs_pool_scsi0QEMU_QEMU_HARDDISK_disk1 -f` will actually succeed after an amount of time has passed by?

**Comment by jgrund** [comment]
correct.

**Comment by brianjmurrell** [comment]
OK.  So, while it seems workable, it feels to me like MMP and `-f` are not completely squaring up with each other and are overlapping in their functionality.

i would think with MMP, `-f` should not be necessary since MMP takes care of the "double checking" that `-f` was providing prior to MMP.

We really should raise this upstream and see what their thoughts are about this in the longer term.

**Pull request merged**
